### ISSUE TITLE
Getting object names

### ISSUE THREAD

**Issue by YuryShkoda** [sassoftware/sas-viya-sdk-js#18]
Hi there,

What is the best way to get all object names included in the report?
I need it in order to get object handlers using `getObjectHandle` method.

Thank you in advance.

**Comment by brmorr** [comment]
Hi @YuryShkoda,

There is not currently any SDK API that allows you to get that information dynamically.  The assumption is that you have a known report, with known (static) object names, that you are embedding.  Can you explain your use case a bit so that we can understand the context a bit better?

**Comment by YuryShkoda** [comment]
Hi @brmorr,
Sure, I have a mixture of data-driven components and VA objects that have been added to the report using VA GUI.
And I would like to track changes (selections) in order to store them and restore them later. So I have no difficulties tracking selections in DDC, but I'm struggling to track changes in objects added using VA GUI.
I hope my description makes sense to you.

**Comment by brmorr** [comment]
Oh, so you are not asking about how to get those names dynamically, through the SDK, as I don't see how that helps you.  You just don't know the object names in the first place?  For that you can utilize the "copy link" option on the object toolbar in Visual Analytics.  This will create a <sas-report-object> tag just like you probably did for the full <sas-report> tag when embedding the report.  From that you can see what the `objectName` property is on that object.  Is this what you need?

**Comment by brmorr** [comment]
That said, how do you plan on restoring selections?  We have the api to get selection state from the objects, but no api to set selections programatically.  It seems like what you are really after is a way to save/restore user state on the report?

**Comment by brmorr** [comment]
@YuryShkoda I never got a clear answer about whether you were actually looking for a dynamic API on the ReportHandle object that would give you a list of all object names.  That seems like what you were asking, but then I didn't see how that helped your case.

**Comment by YuryShkoda** [comment]
I was asking about object names because I had a single route with a generic JS component that has been used for multiple DDCs. But then I created dedicated routes for every DDC and I don't really need object names anymore.

**Comment by brmorr** [comment]
OK, and in that case of a generic route you wanted to handle all of your DDC elements generically, without hard-coding any object names?  Even though you don't need this specifically I do think API on ReportHandle to get this could be useful.  I am going to close this ticket and put this item on our internal list to discuss with product management.  Thanks for the info on your use case.

**Comment by YuryShkoda** [comment]
any time, @brmorr !
