### ISSUE TITLE
Sending message with empty selection

### ISSUE THREAD

**Issue by YuryShkoda** [sassoftware/sas-viya-sdk-js#30]
Hi there,

### Issue
I have an issue with sending an empty selection in SAS VA SDK `1.13.0`.
### Use case (simplified)
I have a DDC that is used to select gender `Man` and `Woman` and a DDC that is used to display statistical data as a table. So changing gender selection and sending the selection using `window.parent.postMessage` works perfectly fine for both Man and Woman selected, only one gender selected, but it doesn't work if no gender is selected.  If a message is posted with an empty selection, SAS responds with the previous selection and it makes sense because gender is required to get the data. But in my particular use case, if no gender is selected, the table should display summarized data for both genders.

Is there a way to get summarized data if an empty selection is sent?
Thank you in advance

**Comment by brmorr** [comment]
Hi @YuryShkoda , I apologize for the extremely long delay on this.  I didn't see this come through when you opened it.  Is this still an issue for you?

**Comment by brmorr** [comment]
@YuryShkoda, I don't think I fully understand your scenario.  Also, this sounds like a general Visual Analytics questions, as I'm assuming your DDC is behaving the same when used in the SDK as it does when viewed in the Visual Analytics application.  Is that correct?  If so, you may be able to get more thorough support for this by entering a SAS technical support ticket.

**Comment by brmorr** [comment]
Closing this stale issue.
