### ISSUE TITLE
Cors error on fetchs

### ISSUE THREAD

**Issue by Dysticus0** [sassoftware/sas-viya-sdk-js#54]
Good morning,
I am creating a portal to access a SAS Viya server.
The portal is a React application, which is located in a local development environment mounted on localhost.
The Viya server is on another computer that I can access through the url.

The problem I have is that when trying to query the server, I receive a Cors error.

_Access to fetch at 'https://viyaserver/SASLogon/oauth/authorize?client_id=sas.SASVisualAnalytics&redirect_uri=%2FSASVisualAnalytics%2F&response_type=code&state=01970f81-9b7c-48f2-bf2a-c462801e3765' (redirected from 'https://viyaserver//SASVisualAnalytics/logon/index.html') from origin 'https://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled._

The button to log in to the portal appears on the screen but the login call still ends with the following error. (More of the same but this time it's a preflight)
![image](https://github.com/sassoftware/sas-viya-sdk-js/assets/108692059/e54f27fe-9442-45e0-bdec-21a84834e8df)

_Access to fetch at 'https://viyaserver/SASLogon/oauth/authorize?client_id=sas.reports&redirect_uri=/reports/&response_type=code&state=xZuELE' (redirected from 'https://viyaserver//reports/') from origin 'https://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled._

The pop up opens but I cannot complete the login
![image](https://github.com/sassoftware/sas-viya-sdk-js/assets/108692059/d7960cb5-d42f-4ba5-b916-879b3bcb46b5)

I have imported the library into the project through CDN

In the main file I evaluate the contentSDK as follows

`  useEffect(() => {
    window.addEventListener("contentSdkComponents.loaded", () => {
        setIsContentSDKReady(true)
    })
  })
`

and then in another file if IsContentSDKReady is true I call the sas component as follows

`<sas-content-tree 
                    url= “viyaserver”
                    authenticationType="credentials"
                    type = 'folderUri'
                    uri = '/folders/folders/485ba120-3241-4dfe-a918-113d7803b1d2'
                >
                </sas-content-tree>
`

The server configuration regarding cors, cookies and csrf is:
Cookies:
Servizi : Globale
sameSite: None

Cors:
Servizi: Globale
Credentials: ON
allowedHeaders : *
allowedMethods : *
allowedOrigins : https://url:port (in this case localhost)

Csrf:
Servizi: Globale
allowebUris: (.+\.)+.+\.sas+\.com,.*

I have tried following the corresponding instructions in the SAS guides, but I still always get the same result. If you need any type of extra information, do not hesitate to ask me.
Thank you.

**Comment by brmorr** [comment]
Hi @Dysticus0 ,

Can you confirm that in your server settings you are setting allowedOrigins to "https://localhost:3000".  It is important that you include the scheme, domain, and port in that setting.  From your comments it seemed like you possibly had only set it to exactly "localhost", which would explain the error.  If you have it set correctly, then it may be that you need to restart all of the services for this to take effect.

**Comment by Dysticus0** [comment]
Hello, good morning, thank you for your response.
In fact, as you mention, I have added the full URLs with and without https protocol.

I added some screenshots about the configuration.

![image](https://github.com/sassoftware/sas-viya-sdk-js/assets/108692059/88d18002-2749-4254-a92d-71ede5c36063)

![image](https://github.com/sassoftware/sas-viya-sdk-js/assets/108692059/84c8a1e7-1da7-41de-839f-f5401f91c248)

![image](https://github.com/sassoftware/sas-viya-sdk-js/assets/108692059/d4c820c1-ec93-4ab5-9ecf-8c7ca6b5638f)


Again, thank you very much for your help.

**Comment by Dysticus0** [comment]
Just for close the issue.
After restarting all environments it worked.
Thanks for the help.
